method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/aaaaaa/aaaa/"
csv_name: "image_attitude.csv"

weights_top_directory: "/home/ssd_dir/aaaaaa/"
weights_file_name: "weights.csv"

infer_log_top_directory: "/home/ssd_dir/aaa/"
infer_log_file_name: "frame_infer_relust.csv"

index_dict_name: index_dict_360x1range_step1deg.csv

window_original_size: 672
window_num: 16
resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 361
dropout_rate: 0.1
corner_threshold: 50
