method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/infer_dataset11_image5000/"
csv_name: "image_attitude.csv"

weights_top_directory: "/home/ssd_dir/cnn_attitude_estimator_log/regression_AirSimNH_uniform_2021_07_19/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/cnn_attitude_estimator_log/infer_log/test_2021_07_01/"
infer_log_file_name: "frame_infer_relust.csv"

index_dict_name: index_dict_360x1range_step1deg.csv

window_original_size: 672
window_num: 10
resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 361
dropout_rate: 0.1
corner_threshold: 30
