method_name: "regression"

save_top_path: "/home/ssd_dir/cnn_attitude_estimator_log/test"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/2021_06_02_image140000/"
valid:
  - "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/2021_06_02_image70000/"
csv_name: "image_attitude.csv"

index_csv_path: "/home/ros_catkin_ws/src/cnn_attitude_estimator/index_dict/index_dict_360x1range_step1deg.csv"

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "Adam"
  lr_cnn: 1e-5
  lr_roll_fc: 1e-4
  lr_pitch_fc: 1e-4
  batch_size: 16
  num_epochs: 2
  dropout_rate: 0.1
  dim_fc_out: 361