method_name: "regression"

save_top_path: "/home/ssd_dir/cnn_attitude_estimator_log/test_AdamW_alpha1e-6_Cross_Entropy_Loss_epoch24"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/2021_06_01_image70000/"
#  - "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/2021_06_02_image140000/"
#  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_03_image140000/"
#  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_04_image70000"
#  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_04_image140000/"
valid:
  - "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/2021_06_02_image70000/"
csv_name: "image_attitude.csv"

index_csv_path: "/home/ros_catkin_ws/src/cnn_attitude_estimator/index_dict/index_dict_360x1range_step1deg.csv"

multiGPU: 0 #1 is ture

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "AdamW"
  loss_function: "CrossEntropyLoss" #CrossEntropyLoss or MSELoss
  lr_cnn: 1e-5
  lr_roll_fc: 1e-5
  lr_pitch_fc: 1e-5
  weight_decay: 0.0001
  batch_size: 32
  num_epochs: 24
  dropout_rate: 0.1
  dim_fc_out: 361
  alpha: 1e-6
  clip_limit: 0.1